Task 10
olgamorozova1/REST pull request #1
Opened 2021-03-21 11:08 UTC by olgamorozova1

2021-03-22 10:38 UTC, EugenBorisik requested changes

2021-03-22 10:38 UTC, EugenBorisik commented on src/main/java/by/issoft/training/Constants/Constants.java
> +package by.issoft.training.Constants;
Package names must be with small letters only

2021-03-22 10:38 UTC, EugenBorisik commented on src/main/java/by/issoft/training/Constants/Constants.java
> +    public static final String GRANT_TYPE = "client_credentials";
I recommend to move all configuration in .properties file

2021-03-22 10:38 UTC, EugenBorisik commented on src/main/java/by/issoft/training/TokenGenerator.java
> +            ex.printStackTrace();
It makes sense to finish execution here, not just print stacktrace

2021-03-22 10:38 UTC, EugenBorisik commented on src/main/java/by/issoft/training/TokenGenerator.java
> +    private String createAccessToken(Scope scope) {
You doesn't store token in any variable after creation

2021-03-23 20:47 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/Constants/Constants.java
> +package by.issoft.training.Constants;
Yes, sorry, fixed.

2021-03-23 20:47 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/Constants/Constants.java
> +    public static final String GRANT_TYPE = "client_credentials";
Moved to config.properties file

2021-03-23 20:50 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/TokenGenerator.java
> +            ex.printStackTrace();
Added exit method.

2021-03-23 20:52 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/TokenGenerator.java
> +    private String createAccessToken(Scope scope) {
Made method public, now calling this method allows to save token  in variable. Removed calling this method from getInstance method.

2021-03-30 10:41 UTC, EugenBorisik requested changes

2021-03-30 10:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +            System.exit(1);
Throw RuntimeException with readable message

2021-03-30 10:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +            properties.load(inputStream);
I recommend to have separate class to access properties and f.e. call can be like:
`Application.get("username");`

2021-03-30 10:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +            tokensStorage.put(scope, token);
It makes sense to verify if token has been already stored in Map before generating it once again

2021-03-30 10:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +    HashMap<Scope, String> tokensStorage = new HashMap<>();
I highly recommend to use interfaces as type of variables:
`Map<Scope, String> tokenStorage = new HashMap<>();`
I understand that it is hard to imagine that realization will changed here and other places, but it is best practice, so I recommend to avoid realization types to avoid issues in your future work

2021-03-30 10:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +    public HashMap<Scope, String> createAccessToken(Scope scope) {
Map

2021-04-01 19:32 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +    public HashMap<Scope, String> createAccessToken(Scope scope) {
Fixed

2021-04-01 19:32 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +    HashMap<Scope, String> tokensStorage = new HashMap<>();
Fixed

2021-04-01 19:34 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +            tokensStorage.put(scope, token);
Added check whether map's already had token with particular scope.

2021-04-01 19:35 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +            properties.load(inputStream);
Created new class to read data from properties and get property value.

2021-04-01 19:36 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/authorization/TokenGenerator.java
> +            System.exit(1);
Added throwing RuntimeException instead of printing stack trace and exit.

2021-04-05 05:13 UTC, EugenBorisik approved these changes

2021-04-05 06:29 UTC, merged