Task30
olgamorozova1/REST pull request #3
Opened 2021-04-04 16:47 UTC by olgamorozova1

2021-04-12 16:21 UTC, EugenBorisik requested changes

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/requests/GetParameters.java
> +public enum GetParameters {
If you've created such class, then give more understandable name

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/BaseTest.java
> +    static UserClient userClient = new UserClient();
Why are they static?

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/ZipCodesClient.java
> +    public String getZipCodes() {
It returns list of zip codes, it makes sense to return list of strings, not just string

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/ZipCodesClient.java
> +    public String retrieveAnyOfAvailableZipCodes(String zipCodes) {
list of zip codes

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/ZipCodesClient.java
> +        post.setRequestBody("[ " + requestBody + " ]");
It is possible to convert list of strings in byte array and then create string from it - it is just example, which you can implement using jackson. Current code "smells". Please update

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/UserClient.java
> +        return get.executeRequest("/users");
I recommend to re-use existing methods, for example:
`return getUsersResponse(null, null);`

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    Patch patch = new Patch();
Looks strange.. Probably it is better to have all static methods in these classes to avoid instance creation

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    }
Code duplication

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    }
You have equals implementation: use just contains. This method must be removed

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +                () -> assertEquals("[\"12345\",\"23456\",\"ABCDE\"]", listOfZipCodes));
1. Compare collections, not strings.
2. This check will fail, if I will expand available zip codes before.

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +    @Order(1)
Ordered tests is way to low understandable code, please remove

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +        listOfZipCodes.add("67890");
I recommend to generate such values

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +        String duplicatedZipCode = "246012";
Generate

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +        String usedZipCode = "246001";
Generate

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public UserDto[] getUsers() {
Try to avoid arrays as such as possible, work with collections

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task30CreateUserTest.java
> +                () -> assertFalse(userClient.checkIfUserExistInArray(listOfUsersAfterAddingDuplicatedUser, duplicatedUser)));
Please think, why such check is incorrect

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task40GetAndFilterUsersTest.java
> +        actualUsers = userClient.getUsers(GetParameters.OlDER_THAN, "20");
You are using int value age as string, Update please

2021-04-12 16:21 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task50UpdateUserTest.java
> +public class Task50UpdateUserTest {
Not reviewed yet.

2021-04-15 21:50 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/utils/JsonConverter.java
> +    }
Fixed

2021-04-15 21:50 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/utils/JsonConverter.java
> +    }
Fixed

2021-04-15 21:50 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/requests/Get.java
> +            getToken(Scope.READ);
Fixed

2021-04-15 21:50 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/requests/GetParameters.java
> +public enum GetParameters {
Renamed

2021-04-15 21:52 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/BaseTest.java
> +    static UserClient userClient = new UserClient();
userClient is static as used in the static method with @BeforeAll annotation in the class Task40GetAndFilterUsersTest. Made  zipCodesClient non static.

2021-04-15 21:53 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/ZipCodesClient.java
> +    public String getZipCodes() {
Fixed

2021-04-15 21:54 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/ZipCodesClient.java
> +    public String retrieveAnyOfAvailableZipCodes(String zipCodes) {
Removed this method as it is not used anymore.

2021-04-15 21:55 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/ZipCodesClient.java
> +        post.setRequestBody("[ " + requestBody + " ]");
Fixed

2021-04-15 21:55 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +        return get.executeRequest("/users");
Fixed

2021-04-15 22:00 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    Patch patch = new Patch();
All of this classes extend abstract class Request with one abstract method executeRequest so if I make it static this abstact class will not make any sense. Should I remove abstact class and make executeRequest static?

2021-04-15 22:02 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    }
Fixed

2021-04-15 22:02 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    }
Removed

2021-04-15 22:03 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +                () -> assertEquals("[\"12345\",\"23456\",\"ABCDE\"]", listOfZipCodes));
Fixed

2021-04-15 22:03 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +    @Order(1)
Removed

2021-04-15 22:03 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +        listOfZipCodes.add("67890");
Created class StringGenerator to generate zip codes. Should user names be generated as well?

2021-04-15 22:04 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +        String duplicatedZipCode = "246012";
Fixed

2021-04-15 22:04 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +        String usedZipCode = "246001";
Fixed

2021-04-15 22:04 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public UserDto[] getUsers() {
Replaced all arrays to lists.

2021-04-15 22:04 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task30CreateUserTest.java
> +                () -> assertFalse(userClient.checkIfUserExistInArray(listOfUsersAfterAddingDuplicatedUser, duplicatedUser)));
Fixed

2021-04-15 22:07 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task30CreateUserTest.java
> +                () -> assertFalse(userClient.checkIfUserExistInArray(listOfUsersAfterAddingDuplicatedUser, duplicatedUser)));
This check is incorrect as it will find user which I added first so I replaced it with check to calculate how much time user with same name and sex exist in the list.

2021-04-15 22:14 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task40GetAndFilterUsersTest.java
> +        actualUsers = userClient.getUsers(GetParameters.OlDER_THAN, "20");
I fixed only type of patameter for methods. When URIBuilder creates URI  this int convers to String as URIBuilder.setParameter() accepts only Strings. I hope you meant this as I could not find appropriate method to setParameters as int. If I'm wrong please give a tip :)

2021-04-19 06:41 UTC, EugenBorisik requested changes

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/utils/JsonConverter.java
> +        return listOfObjects;
`return convertJsonToObject(EntityUtils.toString(responseBodyEntity), tClass);`

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/requests/Request.java
> +    public String getToken() {
Make it private, remove calls from Get/Post/etc. classes

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/requests/Request.java
> +        this.scope = scope;
Add one more line: authHeader = getToken();

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/requests/Request.java
> +        authHeader = "Bearer " + token.get(scope);
Remove this line

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task20ZipCodesTest.java
> +        listOfZipCodes.add("67890");
Uniqueness for users is complex key (name + sex). It means that it is better to generate names too.

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public List<UserDto> getUsers(ParametersForGetRequest parameters, String value) {
For better readability: String value -> String sex

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public List<UserDto> getUsers(ParametersForGetRequest parameters, int value) {
For better readability: int value -> int age

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/requests/Get.java
> +    }
You need to create 1 method, which gets all 3 possible params and then create wrapper methods in client like:
`... getUsersWithSex(Sex sex) {
return getUsers(sex, null, null);
}`

2021-04-19 06:41 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task50UpdateUserTest.java
> +public class Task50UpdateUserTest extends BaseTest {
I'm okay with all provided tests for this task, but please add checks for zip codes in each test.

2021-04-21 07:20 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/utils/JsonConverter.java
> +        return listOfObjects;
Fixed

2021-04-21 07:20 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/requests/Request.java
> +    public String getToken() {
Fixed

2021-04-21 07:20 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/requests/Request.java
> +        this.scope = scope;
Fixed

2021-04-21 07:20 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/requests/Request.java
> +        authHeader = "Bearer " + token.get(scope);
Fixed

2021-04-21 07:20 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public List<UserDto> getUsers(ParametersForGetRequest parameters, String value) {
Fixed

2021-04-21 07:20 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public List<UserDto> getUsers(ParametersForGetRequest parameters, int value) {
Fixed

2021-04-21 07:21 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/requests/Get.java
> +    }
Fixed

2021-04-22 15:14 UTC, EugenBorisik approved these changes

2021-04-22 17:28 UTC, merged