Task70
olgamorozova1/REST pull request #5
Opened 2021-05-03 07:08 UTC by olgamorozova1

2021-05-04 07:47 UTC, EugenBorisik requested changes

2021-05-04 07:47 UTC, EugenBorisik commented on src/main/java/by/issoft/training/utils/Converter.java
> +    public static <T> void convertListToJsonFile(List<T> list, String pathname) {
Change to wildcard:
`public static void convertListToJsonFile(List<?> list, String pathname)`

2021-05-04 07:47 UTC, EugenBorisik commented on src/main/java/by/issoft/training/utils/Converter.java
> +    public static <T> String convertListToJson(List<T> list) {
Remove this method, use convertObjectToJson where needed

2021-05-04 07:47 UTC, EugenBorisik commented on bug_reports/BugReportsTask70
> +1. 500 error is received when post upload request with header Content-type: "multipart/form-data" is sent.
This bug doesn't exist

2021-05-04 07:47 UTC, EugenBorisik commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public <T> HttpResponse uploadUsers(List<T> listOfObjects) {
Change to wildcard:
`public HttpResponse uploadUsers(List<?> listOfObjects)`

2021-05-04 07:47 UTC, EugenBorisik commented on src/main/java/by/issoft/training/requests/Post.java
> +            builder.addBinaryBody("file", new File(pathname));
multipart/form-data works:
`File file = new File(pathname);
 builder.addBinaryBody("file", file, ContentType.MULTIPART_FORM_DATA, file.getName());`

2021-05-04 07:47 UTC, EugenBorisik commented on src/main/java/by/issoft/training/requests/Post.java
> +    public <T> HttpResponse executeUploadRequest(String path, List<T> listOfObjects) {
Use wildcard:
`public HttpResponse executeUploadRequest(String path, List<?> listOfObjects)`

2021-05-04 07:47 UTC, EugenBorisik commented on src/main/java/by/issoft/training/test/Task70UploadUsersTest.java
> +public class Task70UploadUsersTest extends BaseTest {
Add one more test for 400 response code

2021-05-04 18:51 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/utils/Converter.java
> +    public static <T> void convertListToJsonFile(List<T> list, String pathname) {
Fixed

2021-05-04 18:51 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/utils/Converter.java
> +    public static <T> String convertListToJson(List<T> list) {
Removed

2021-05-04 18:51 UTC, olgamorozova1 commented on bug_reports/BugReportsTask70
> +1. 500 error is received when post upload request with header Content-type: "multipart/form-data" is sent.
Not a bug, deleted

2021-05-04 18:51 UTC, olgamorozova1 commented on bug_reports/BugReportsTask70
> +1. 500 error is received when post upload request with header Content-type: "multipart/form-data" is sent.
Not a bug, deleted

2021-05-04 18:52 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public <T> HttpResponse uploadUsers(List<T> listOfObjects) {
Fixed

2021-05-04 18:53 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/requests/Post.java
> +            builder.addBinaryBody("file", new File(pathname));
Discussed, no changes are needed.

2021-05-04 18:54 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/requests/Post.java
> +    public <T> HttpResponse executeUploadRequest(String path, List<T> listOfObjects) {
Fixed

2021-05-04 18:54 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/test/Task70UploadUsersTest.java
> +public class Task70UploadUsersTest extends BaseTest {
Added new test.

2021-05-06 11:46 UTC, EugenBorisik approved these changes

2021-05-12 17:08 UTC, merged