Replaced methods return values from HttpResponse to Pairs
olgamorozova1/REST pull request #7
Opened 2021-05-12 21:30 UTC by olgamorozova1

2021-05-13 08:05 UTC, EugenBorisik requested changes
@olgamorozova1 please close response in clients code

2021-05-13 19:14 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +    public Pair<Integer, List<UserDto>> createResponseAndBodyPairFromGetUsersRequest(CloseableHttpResponse response) {
Fixed

2021-05-13 19:14 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +        return responseCodeAndBody;
Fixed

2021-05-13 19:14 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/UserClient.java
> +        return responseCodeAndBody;
Fixed

2021-05-13 19:14 UTC, olgamorozova1 commented on src/main/java/by/issoft/training/clients/ZipCodesClient.java
> +        return responseCodeAndBody;
Fixed

2021-05-14 08:20 UTC, EugenBorisik approved these changes

2021-05-14 08:23 UTC, merged